### ISSUE TITLE
Ошибка сегментирования

### ISSUE THREAD

**Issue by kirillclone** [janvarev/Irene-Voice-Assistant#30]
Решыл изменить движок на rhvoice и получаю ошыбку "Ошибка сегментирования" как исправить ?

**Comment by kirillclone** [comment]
"Аварийный останов"

**Comment by kirillclone** [comment]
"Process finished with exit code 134 (interrupted by signal 6: SIGABRT)"

**Comment by kirillclone** [comment]
talgat :  {'no': 19, 'name': 'Talgat', 'lang': 'tt', 'gender': 'male', 'country': 'RU'}
Input (cmd):  ирина привет

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by janvarev** [comment]
Неактивно.
