### ISSUE TITLE
Ошибка Error opening RawInputStream

### ISSUE THREAD

**Issue by fgsfds** [janvarev/Irene-Voice-Assistant#32]
Windows 10 
Python 3.10.5

![image](https://user-images.githubusercontent.com/4870330/176004112-3020f3c2-f989-4e71-9e87-7e9fef70ac9d.png)

**Comment by janvarev** [comment]
Просьба гуглить ошибку перед тем как постить сообщение.
По первой ссылке по ошибке выдается, например, это:
https://github.com/PortAudio/portaudio/issues/360

![image](https://user-images.githubusercontent.com/18393788/176117571-f699f46b-c7c5-4461-ae60-e0de57561c31.png)

Помогло?
