### ISSUE TITLE
Список фраз для дообучения нейросети VOSK

### ISSUE THREAD

**Issue by janvarev** [janvarev/Irene-Voice-Assistant#41]
Нам решили помочь и дообучить VOSK на распознавание наших фраз. Но это разовая акция, поэтому давайте подойдем к делу обстоятельно.

Вы можете добавить в это ISSUE фразы, которые считаете, что было бы хорошо часто использовать в плагинах.
1. Формат поста - 
(Краткое описание в 1 строчку:)
пустая строка
<список фраз, по 1 на строчку>

2. Фразы принимаются 25 и 26 января, потом я сформирую финальный список из того, что сочту нужным (сорри за диктатуру, но так), и отправлю Николаю, скорее всего 27 утром-днем.

3. Если вам нравится какой-то сет - лайкните его смайликом. Это будет учитываться.

4. Добавляйте те фразы, которые считаете относительно универсальными для разных плагинов/ситуаций. Частные случаи я скорее всего не включу.

5. Пожалуйста, просмотрите список фраз других людей и старайтесь не добавлять дубликаты.

---
UPD:

М-м. Ну, давайте добавим немного имен голосового помощника для вариативности, ок.

Предположительно нужно еще:
- 2-3 женских имени
- 2-3 мужских имени

ВАЖНО!
- Имена НЕ должны смешиваться с бытовой речью; предположительно, быть распространенными.

Пример:
- Коля - не очень; Николай - хорошо
- Оля - не очень; Оксана - ок.

**Comment by janvarev** [comment]
Имена Ирины:

ирина
ирины
ирину

**Comment by janvarev** [comment]
Фразы из базовых плагинов:

игра больше меньше
привет
доброе утро
пауза
паузу
дальше
вперед
назад
стоп
без звука
выключи звук
со звуком
тише
громче
чуть тише
чуть громче
сильно тише
сильно громче
выключи плеер
закрой плеер
пробел
запусти плеер
мультик
сериал
подбрось
брось
поставь таймер
таймер
погода
прогноз погоды
прогноз погода
ближайший поезд
электричка
электрички

**Comment by janvarev** [comment]
Числительные:

ноль
один
два
три
четыре
пять
шесть
семь
восемь
девять
десять
одиннадцать
двенадцать
тринадцать
четырнадцать
пятнадцать
шестнадцать
семнадцать
восемнадцать
девятнадцать
двадцать
двадцать один
двадцать два
двадцать три
двадцать четыре
двадцать пять
двадцать шесть
двадцать семь
двадцать восемь
двадцать девять
тридцать
тридцать один
тридцать два
тридцать три
тридцать четыре
тридцать пять
тридцать шесть
тридцать семь
тридцать восемь
тридцать девять
сорок
сорок один
сорок два
сорок три
сорок четыре
сорок пять
сорок шесть
сорок семь
сорок восемь
сорок девять
пятьдесят
пятьдесят один
пятьдесят два
пятьдесят три
пятьдесят четыре
пятьдесят пять
пятьдесят шесть
пятьдесят семь
пятьдесят восемь
пятьдесят девять
шестьдесят
шестьдесят один
шестьдесят два
шестьдесят три
шестьдесят четыре
шестьдесят пять
шестьдесят шесть
шестьдесят семь
шестьдесят восемь
шестьдесят девять
семьдесят
семьдесят один
семьдесят два
семьдесят три
семьдесят четыре
семьдесят пять
семьдесят шесть
семьдесят семь
семьдесят восемь
семьдесят девять
восемьдесят
восемьдесят один
восемьдесят два
восемьдесят три
восемьдесят четыре
восемьдесят пять
восемьдесят шесть
восемьдесят семь
восемьдесят восемь
восемьдесят девять
девяносто
девяносто один
девяносто два
девяносто три
девяносто четыре
девяносто пять
девяносто шесть
девяносто семь
девяносто восемь
девяносто девять
сто
двести
триста
четыреста
пятьсот
шестьсот
семьсот
восемьсот
девятьсот
тысяча
тысячи
миллион
миллиард

**Comment by SergeyMi37** [comment]
Имена ассистента:------------
ирэн

лика
лики
лику

гоша
гоши
гошу

жора
жоры
жору

Слова:------------------
напомни
что можешь
играть
читать
новости
сказки
книги
смотреть
найди

**Comment by videosplitter** [comment]
Имена:------------
Нейродом
Нэйра
Бэрримор
Альфред
Дживс
Гудвин
Джинн
Хоттабыч
Фрекен Бок

Слова:------------
я хочу
я хочу чтобы стало
мне нужен
мне 
сделай

жарко
холодно
прохладно
зябко
душно
свежо
свежий воздух
светло
темно
весело

включи
запусти
выключи
останови
хватит
скажи
расскажи
назови
позови
начни
пора
открой
закрой
установи
напомни
запомни
запиши
добавь в список

построй маршрут
покажи на карте
как проехать до 
отправь
пришли

какой
какие
какое
какая
сколько 
во сколько
когда
где
куда
как
что
что показывает

датчик
температура
температуры
влажность
влажности
погода
яркость
режим
будильник
таймер
статус

процент
процентов
процента
градус
градуса
градусов

ночник
лампочка
лампочку
свет 
торшер
гирлянда
гирлянду
подсветка
подсветку

музыка
музыку
радио
колонка
колонку
пылесос
чайник
телевизор
телек
кондиционер
кондер
кондей
увлажнитель
увлажнителя
увлажнители
очиститель
розетка
розетку
машина
машину
машинка
машинку
авто
автомобиль
двигатель
посудомойка
посудомойку
стиральная машина
стиралка
стиралку
камера
камеру
замок

везде
здесь
дома
в квартире
в доме
снаружи
внутри
кухня
на кухне
спальня
в спальне
зал
в зале
гостиная
в гостиной
холл
в холле
коридор
в коридоре
туалет
в туалете
ванная
в ванной
комната
в комнате
детская
в детской
на улице
во дворе

первый
второй
третий
четвертый
пятый
шестой
седьмой
восьмой
девятый
десятый

номер

**Comment by byef** [comment]
люся
люси
люсиль
джарвис
джарвиса

дата
время
времени
сколько времени
минуты
минут
часы
часов
час
который
который час
какой
секунды
секунд
игра
игра больше меньше
больше
меньше
привет
доброе утро
салют
добрый вечер
доброй ночи
спокойной ночи
чао
пока
адью
пауза
паузу
дальше
далее
вперед
назад
стоп
пуск
без звука
включи
включи звук
выключи
выключи звук
со звуком
тише
громче
чуть тише
чуть громче
сильно тише
сильно громче
выключи плеер
закрой плеер
пробел
запусти плеер
включи плеер
телевизор
ресивер
модем
радио
канал
мультик
сериал
фильм
сезон
серия
ютуб
вход
выход
переключи
перезапусти
рестарт
старт
остановить
останови
прибавь
убавь
прибавить
убавить
скрыть
показать
скрой
покажи
найди
подбрось
брось
сравнить
сравни
поставь таймер
таймер
будильник
поставь будильник
погода
прогноз погоды
прогноз погода
ближайший поезд
электричка
электрички
город
в городе
дом
этаж
квартира
гостиная
в гостиной
прихожая
в прихожей
коридор
в коридоре
спальня
в спальне
детская
в детской
кабинет
в кабинете
балкон
на балконе
лоджия
на лоджии
санузел
в санузле
туалет
в туалете
ванная
в ванной
пылесос
чайник
роутер
бойлер
градусов
градусы
уровень
дверь
открой дверь
закрой дверь
открой окно
закрой окно
открыть
открой
закрыть
закрой
включить
выключить
запустить
остановить
запусти
останови
задай
сцена
задай сцену
включи сцену
подбрось монетку
брось монетку
брось
бросить
кубик
число
какое
какой
какая
случайное число
рандом
режим ночь
режим день
запусти режим
смени режим
спать
включи режим
выключи режим
показания
данные
датчик
показания датчика
теплее
холоднее
солнце
луна
шторы
закрой шторы
открой шторы
жалюзи
кондиционер
бризер
воздух
свет
включи свет
выключи свет
яркость
прибавь яркость
убавь яркость
скажи
сделай
светлее
темнее
текст
прочитай текст
озвучить
озвучь
озвучь текст
читать
буфер
книга
аудиокнигу
температуру
влажность
освещение
холодильник
вытяжка
включи вытяжку
приставка
приставку
плойка
плойку
домофон
камера
камеру
снимок
фото
кадр
видео
аудио
всё
ничего
надо
не надо
отменить
отмена
отмени
день
ночь
утро
вечер
полдень
полночь
понедельник
вторник
среда
четверг
пятница
суббота
воскресенье
январь
февраль
март
апрель
май
июнь
июль
август
сентябрь
октябрь
ноябрь
декабрь
неделя
недели
месяц
год

**Comment by janvarev** [comment]
Доп слова

кузя

оксана
оксане
оксану

акции
список
добавь
очисть

яндекс
гугл
википедия
ютуб
вики

сказка

яндекс
гугл
википедия
ютуб
вики

**Comment by janvarev** [comment]
Список закончен, внёс всё.
