### ISSUE TITLE
plugin_tts_silero_v4.py правильная версия torch 

### ISSUE THREAD

**Issue by Ivan-Firefly** [janvarev/Irene-Voice-Assistant#53]
Для модели V4 нужен torch 2.0+, инчае не запускатся модель.

В комментариях к коду (4 строка) стоит torch 1.10+ (как и в requirements-docker.txt)

Источник https://github.com/snakers4/silero-models?tab=readme-ov-file#dependencies-1

**Comment by janvarev** [comment]
fixed
