### ISSUE TITLE
COMError: (-2147024893, 'Системе не удается найти указанный путь.', (None, None, None, 0, None))

### ISSUE THREAD

**Issue by gangfv** [janvarev/Irene-Voice-Assistant#7]

**Comment by 6GganG** [comment]
How to fix the error?

**Comment by 6GganG** [comment]
com_error: (-2147352567, 'Ошибка.', (0, None, None, None, 0, -2147024893), None)

**Comment by janvarev** [comment]
Не уверен. В какой момент появляется ошибка?
Предварительно предполагаю, что в момент рендера речи движком. Тогда надо поменять TTS c pyttsx (видимо, не установлен русский TTS в Windows) на, например, rhvoice.

**Comment by janvarev** [comment]
Закрыто за неактивностью.
