### ISSUE TITLE
UnboundLocalError: local variable 'haveRun' referenced before assignment и sh: строка 1: aplay: команда не найдена

### ISSUE THREAD

**Issue by arlcrow123** [janvarev/Irene-Voice-Assistant#9]
JAA.PY v1.5 class created!
JAA PLUGIN: Core plugin 1.9 (core) started!
JAA PLUGIN: Игра больше меньше 1.0 (plugin_gamemoreless) started!
JAA PLUGIN: TTS pyttsx 1.1 (plugin_tts_pyttsx) started!
JAA PLUGIN: Команды управления мультимедия 1.2 (plugin_mediacmds) started!
JAA PLUGIN: Привет 1.0 (plugin_greetings) started!
JAA PLUGIN: Таймер 1.2 (plugin_timer) started!
JAA PLUGIN: MPC-HC проигрывание мультиков 1.2 (plugin_mpchcmult) started!
JAA PLUGIN: TTS console (for debug) 1.0 (plugin_tts_console) started!
JAA PLUGIN: Рандом 1.0 (plugin_random) started!
JAA PLUGIN: Дата и время 1.0 (plugin_datetime) started!
OWM: нужен api_key для получения погоды! пока отключено
JAA PLUGIN: Погода (open weather map) 1.0 (plugin_weatherowm) started!
JAA PLUGIN: Яндекс Расписания 1.0 (plugin_yandex_rasp) started!
VoiceAssistantCore v4.0: run OFFLINE
TTS engines:  dict_keys(['pyttsx', 'console'])
Commands list:  dict_keys(['игра больше меньше', 'пауза|паузу', 'дальше|вперед', 'назад', 'без звука|выключи звук|со звуком|без мука', 'тише', 'громче', 'чуть тише', 'чуть громче', 'сильно тише', 'сильно громче', 'выключи плеер|закрой плеер', 'пробел', 'привет|доброе утро', 'таймер|тайгер', 'запусти плеер', 'мультик', 'подбрось|брось', 'дата', 'время', 'погода', 'прогноз погоды|прогноз погода', 'ближайший поезд|электричка|электрички'])
Assistant names:  ['ирина', 'ирины', 'ирину']
Input (cmd):  ирина время
Full dictionary is not installed for 'ru'
sh: строка 1: aplay: команда не найдена
Can you check if your microphone is on, please?
Traceback (most recent call last):
  File "/home/arlcrow123/Irene-Voice-Assistant/vacore.py", line 268, in run_input_str
    voice_input = voice_input_str.split(" ")
AttributeError: 'NoneType' object has no attribute 'split'

Traceback (most recent call last):
  File "/home/arlcrow123/Irene-Voice-Assistant/runva_speechrecognition.py", line 65, in <module>
    core.run_input_str(voice_input_str)
  File "/home/arlcrow123/Irene-Voice-Assistant/vacore.py", line 306, in run_input_str
    return haveRun
UnboundLocalError: local variable 'haveRun' referenced before assignment

Arch Linux, ядро 5.16.15-arch1-1

**Comment by janvarev** [comment]
1. sh: строка 1: aplay: команда не найдена - здесь непонятно в чем дело
2. voice_input = voice_input_str.split(" ")
AttributeError: 'NoneType' object has no attribute 'split'
Только что пофиксил - добавил проверку на None на входе. Хотя по идее None не должно было передаваться, но вот, передается.

3. File "/home/arlcrow123/Irene-Voice-Assistant/runva_speechrecognition.py", line 65, in
core.run_input_str(voice_input_str)
Может, проблема в подключении speechrecognition? Там обычно что-то нетривиальное с зависимостями, может, микрофон не слышит.
Я обычно работаю на runva_vosk.

**Comment by arlcrow123** [comment]
решил проблему с aplay установкой пакета alsa-utils
